### ISSUE TITLE
Could not load file or assembly 'LibGit2Sharp' and "remote authentication required but no callback set"

### ISSUE THREAD

**Issue by tobey74** [Dutchskull/Aspire.PolyRepo#22]
Hi, I am trying to follow your examples from your readme to add projects from git repos to my Aspire AppHost.
I have tried adding both repos from the organization I am part of and from my own GitHub account but both fails.

First I got this error:
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'LibGit2Sharp, 
  Version=0.30.0.0, Culture=neutral, 
  PublicKeyToken=7cbde695407f0333'. 
The system cannot find the file specified.
``` 

So I added the package manually to my AppHost project:
```
Install-Package LibGit2Sharp -Version 0.30.0
``` 

But then builder.AddRepository throws exception **remote authentication required but no callback set**
```
LibGit2Sharp.LibGit2SharpException
  HResult=0x80131500
  Message=remote authentication required but no callback set
  Source=LibGit2Sharp
  StackTrace:
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
   at Dutchskull.Aspire.PolyRepo.ProcessCommandExecutor.CloneGitRepository(String gitUrl, String resolvedRepositoryPath, String branch)
   at Dutchskull.Aspire.PolyRepo.RepositoryConfigExtensions.CloneRepository(RepositoryConfig repositoryConfig)
   at Dutchskull.Aspire.PolyRepo.RepositoryConfigExtensions.SetupRepository(RepositoryConfig gitRepositoryConfig)
   at Dutchskull.Aspire.PolyRepo.RepositoryConfigExtensions.InitializeRepository(Action`1 configureGitRepository, String repositoryUrl)
   at Dutchskull.Aspire.PolyRepo.ProjectResourceBuilderExtensions.AddRepository(IDistributedApplicationBuilder builder, String name, String repositoryUrl, Action`1 configureGitRepositoryBuilderAction)
   at Program.<Main>$(String[] args) in C:\Dev\Repos\Pida\src\Pida.AppHost\Program.cs:line 41
``` 

I get this error no matter if I try adding repo from my private GitHub or the organization I am part of but here example with my own GitHub account and repo:

```
var myRepo = builder.AddRepository(
    "my-movies-api",
    "https://github.com/PrivateGitHubAccount/my-movies.git",
    c => c.WithDefaultBranch("main").WithTargetPath("c:/dev/git"));

Or with organization

var myOrgRepo = builder.AddRepository(
    "api",
    "https://github.com/OurOrganization/some-project.git",
    c => c.WithDefaultBranch("main").WithTargetPath("c:/dev/git"));
``` 

I cannot see a way how to authenticate with GitHub or provide som Credentials?

I do have my GitHub credentials stored as environment variables like GHP_TOKEN and GHP_USER.

**Comment by WhiteOlivierus** [comment]
Thank you for posting an issue, I will be investigating this.

**Comment by WhiteOlivierus** [comment]
@tobey74 I have made a fix for this, I haven't had the time to test this. This will probably come some time next week. Or if you might have some time please check if this works.

**Comment by tobey74** [comment]
@WhiteOlivierus Hi Olivier, I have tried connecting to GitHub with your updated code but without luck I'm sorry :)
Your latest NuGet push failed so I tried cloning your code locally but even then I cannot find a way to assign the GitConfigBuilder with my Username and Password set to a RepositoryConfigBuilder because the GitConfig is not exposed but is private.
Also, you create always a new GitConfig object on line 27 when the RepositoryConfigBuilder is build.
So for the moment I don't see a way to provide the GitHub credentials - I have tried making the WithGitConfig public on line 64 but still no luck with cloning my repo.

**Comment by WhiteOlivierus** [comment]
Thank you for looking at it, I am still working on this but since I am doing this in my spare time this can take sometime.

I have done a little bit of work that adds it to the sample now and seems to work without authentication.

**Comment by tobey74** [comment]
Absolutely no rush from my side Olivier, I'm just looking forward to follow your project extending Aspire :)

**Comment by WhiteOlivierus** [comment]
I have tested this internally with private projects and it seems to work now. I wil be updating documentation and merging this.
